name: Weekly Learning Plan

on:
  schedule:
    - cron: "0 7 * * 1"   # Runs every Monday at 07:00 UTC
  workflow_dispatch:       # Allows manual run from GitHub UI

jobs:
  generate_plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate weekly learning plan
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: python agent.py
